# Generated by Django 2.0.5 on 2018-08-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_project', '0002_user1'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Contact', models.IntegerField()),
                ('Email', models.CharField(max_length=200)),
                ('Lead_from', models.CharField(max_length=200)),
                ('Called_by', models.CharField(max_length=200)),
                ('Course', models.CharField(max_length=200)),
                ('Interview_type', models.CharField(max_length=200)),
                ('Education', models.CharField(max_length=200)),
                ('Specialization', models.CharField(max_length=200)),
                ('year_of_passing', models.IntegerField()),
                ('fresher_experience', models.CharField(max_length=200)),
                ('Time_in', models.IntegerField()),
                ('Time_out', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='user1',
        ),
    ]
